PUT http://localhost:5000/games/1
Content-Type: application/json

{ 
    "name" : "modified test game", 
    "price" : 1000, 
    "category" : 1,
    "description" : "modified test description",
    "state" : 0
}